### ISSUE TITLE
0.6.0 built failed

### ISSUE THREAD

**Issue by maymage** [flathub/io.gitlab.caveman250.headlines#1]
Hi, 

this is not a bug report, but just to let - in case you did not already - know that the much awaited 0.6.0 built has failed here. 

Best

**Comment by hfiguiere** [comment]
one tip I can give for maintainers is to make PR so they can run the build once automatically. It's here for that.

Sadly we still don't get notified if the build fail on the main branches.

**Comment by caveman250** [comment]
Seems one of the dependencies for gst-libav has gone offline :( Will see if theres a newer version i should be using or if i just need to wait

**Comment by caveman250** [comment]
Thabks for the tip about using PRs, will do that in future :D

**Comment by hfiguiere** [comment]
I see it here
https://gitlab.freedesktop.org/gstreamer/gst-libav

**Comment by caveman250** [comment]
According to the log the issue is https://git.libav.org/gas-preprocessor.git which i assume is being dragged in by gst-libav. Will have to look more in depth after work

**Comment by maymage** [comment]
Just updated to 0.60 from flathub. 

Thanks for the fix.
